package stream

import (
	"strconv"
	"strings"
)

func (s *stream) Add(key string, id string, values map[string]string) (string, error) {
	lastId := s.lastIdMap[key]

	// Handle auto-generation of sequence number
	if strings.Contains(id, "*") {
		generatedId, err := s.autoGenerated(lastId, id)
		if err != nil {
			return "", err
		}
		if generatedId == "" {
			return "", &IDError{Message: "ERR Invalid ID format"}
		}
		id = generatedId
	}

	if id == "0-0" {
		return "", &IDError{Message: "ERR The ID specified in XADD must be greater than 0-0"}
	}

	if !s.validate(lastId, id) {
		return "", &IDError{Message: "ERR The ID specified in XADD is equal or smaller than the target stream top item"}
	}

	entry := Entry{
		ID:     id,
		Values: values,
	}
	s.streamMap[key] = append(s.streamMap[key], entry)
	s.lastIdMap[key] = id
	return id, nil
}

func (s *stream) CheckExist(key string) (bool, bool) {
	entries, ok := s.streamMap[key]
	return ok && len(entries) > 0, ok
}

func (s *stream) Get(key string) ([]Entry, bool) {
	entries, ok := s.streamMap[key]
	return entries, ok
}

func (s *stream) autoGenerated(lastId string, id string) (string, error) {
	if id == "*" {
		if lastId == "" {
			return "0-1", nil
		}
		parts := strings.Split(lastId, "-")
		if len(parts) != 2 {
			return "", nil
		}
		lastSeq, _ := strconv.Atoi(parts[1])
		return parts[0] + "-" + strconv.Itoa(lastSeq+1), nil
	}

	v2 := strings.Split(id, "-")

	if len(v2) == 2 && v2[0] != "*" && v2[1] == "*" {
		newTime, _ := strconv.Atoi(v2[0])

		if lastId == "" {
			if newTime == 0 {
				return "0-1", nil
			}
			return v2[0] + "-0", nil
		}

		lastParts := strings.Split(lastId, "-")
		if len(lastParts) != 2 {
			return "", nil
		}
		lastTime, _ := strconv.Atoi(lastParts[0])
		lastSeq, _ := strconv.Atoi(lastParts[1])

		if newTime < lastTime {
			return "", &IDError{Message: "ERR The ID specified in XADD is equal or smaller than the target stream top item"}
		}

		if newTime > lastTime {
			return v2[0] + "-0", nil
		}

		return v2[0] + "-" + strconv.Itoa(lastSeq+1), nil
	}

	return "", nil
}

func (s *stream) validate(lastId, id string) bool {
	if lastId == "" {
		return true
	}

	v1 := strings.Split(lastId, "-")
	v2 := strings.Split(id, "-")

	if len(v1) != 2 || len(v2) != 2 {
		return false
	}

	tv11, _ := strconv.Atoi(v1[0])
	tv12, _ := strconv.Atoi(v1[1])
	tv21, _ := strconv.Atoi(v2[0])
	tv22, _ := strconv.Atoi(v2[1])

	if tv21 > tv11 {
		return true
	} else if tv21 == tv11 {
		return tv22 > tv12
	}
	return false
}
