package stream

import (
	"strconv"
	"strings"
	"time"
)

func (s *stream) Add(key string, id string, values map[string]string) (string, error) {
	lastId := s.lastIdMap[key]

	if strings.Contains(id, "*") {
		generatedId, err := s.autoGenerated(lastId, id)
		if err != nil {
			return "", err
		}
		if generatedId == "" {
			return "", &IDError{Message: "ERR Invalid ID format"}
		}
		id = generatedId
	}

	if id == "0-0" {
		return "", &IDError{Message: "ERR The ID specified in XADD must be greater than 0-0"}
	}

	if !s.validate(lastId, id) {
		return "", &IDError{Message: "ERR The ID specified in XADD is equal or smaller than the target stream top item"}
	}

	keyOrder := make([]string, 0, len(values))
	for k := range values {
		keyOrder = append(keyOrder, k)
	}

	entry := Entry{
		ID:       id,
		Values:   values,
		KeyOrder: keyOrder,
	}
	s.streamMap[key] = append(s.streamMap[key], entry)
	s.lastIdMap[key] = id

	waitingClients := s.waiting[key]
	s.waiting[key] = nil

	go func(clients []*WaitingClient, newEntry Entry, k string) {
		requeue := []*WaitingClient{}
		for _, client := range clients {
			client.ch <- newEntry
			done := <-client.done
			if !done {
				requeue = append(requeue, client)
			} else {
				close(client.ch)
			}
		}
		if len(requeue) > 0 {
			s.waiting[k] = requeue
		}
	}(waitingClients, entry, key)

	return id, nil
}

func (s *stream) CheckExist(key string) (bool, bool) {
	entries, ok := s.streamMap[key]
	return ok && len(entries) > 0, ok
}

func (s *stream) Get(key string) ([]Entry, bool) {
	entries, ok := s.streamMap[key]
	return entries, ok
}

func (s *stream) Range(key string, startId string, endId string) ([]Entry, bool) {
	entries, ok := s.streamMap[key]
	if !ok {
		return []Entry{}, false
	}

	startParts := strings.Split(startId, "-")
	endParts := strings.Split(endId, "-")

	startTime, _ := strconv.ParseInt(startParts[0], 10, 64)
	startSeq := int64(0)
	if len(startParts) > 1 && startParts[1] != "" {
		seq, _ := strconv.ParseInt(startParts[1], 10, 64)
		startSeq = seq
	}

	endTime, _ := strconv.ParseInt(endParts[0], 10, 64)
	endSeq := int64(9223372036854775807)
	if len(endParts) > 1 && endParts[1] != "" {
		seq, _ := strconv.ParseInt(endParts[1], 10, 64)
		endSeq = seq
	}

	var result []Entry
	for _, entry := range entries {
		parts := strings.Split(entry.ID, "-")
		time, _ := strconv.ParseInt(parts[0], 10, 64)
		seq, _ := strconv.ParseInt(parts[1], 10, 64)

		if (time > startTime || (time == startTime && seq >= startSeq)) &&
			(time < endTime || (time == endTime && seq <= endSeq)) {
			result = append(result, entry)
		}
	}

	return result, len(result) > 0
}

func (s *stream) ReadGreater(key string, id string) ([]Entry, bool) {
	entries, ok := s.streamMap[key]
	if !ok {
		return []Entry{}, false
	}

	// Parse the ID to get time and sequence
	parts := strings.Split(id, "-")
	refTime, _ := strconv.ParseInt(parts[0], 10, 64)
	refSeq := int64(0)
	if len(parts) > 1 && parts[1] != "" {
		seq, _ := strconv.ParseInt(parts[1], 10, 64)
		refSeq = seq
	}

	var result []Entry
	for _, entry := range entries {
		entryParts := strings.Split(entry.ID, "-")
		entryTime, _ := strconv.ParseInt(entryParts[0], 10, 64)
		entrySeq, _ := strconv.ParseInt(entryParts[1], 10, 64)

		// Return entries with ID > reference ID (exclusive)
		if (entryTime > refTime) || (entryTime == refTime && entrySeq > refSeq) {
			result = append(result, entry)
		}
	}

	return result, len(result) > 0
}

func (s *stream) Stream(key string, ids []string) ([]Entry, bool) {
	entries, ok := s.streamMap[key]
	if !ok {
		return []Entry{}, false
	}
	var result []Entry
	for _, entry := range entries {
		for _, id := range ids {
			if entry.ID == id {
				result = append(result, entry)
			}
		}
	}

	return result, len(result) > 0
}

func (s *stream) Block(key, id string, exp float64) Entry {
	client := &WaitingClient{
		ch:   make(chan Entry),
		done: make(chan bool),
	}
	s.waiting[key] = append(s.waiting[key], client)

	checkID := func(refID, entryID string) bool {
		refParts := strings.Split(refID, "-")
		entryParts := strings.Split(entryID, "-")
		refTime, _ := strconv.ParseInt(refParts[0], 10, 64)
		refSeq := int64(0)
		if len(refParts) > 1 && refParts[1] != "" {
			seq, _ := strconv.ParseInt(refParts[1], 10, 64)
			refSeq = seq
		}
		entryTime, _ := strconv.ParseInt(entryParts[0], 10, 64)
		entrySeq, _ := strconv.ParseInt(entryParts[1], 10, 64)
		return (entryTime > refTime) || (entryTime == refTime && entrySeq > refSeq)
	}

	processEntry := func() Entry {
		select {
		case entry := <-client.ch:
			if checkID(id, entry.ID) {
				client.done <- true // Done, logout
				return entry
			} else {
				client.done <- false // Not ready, keep waiting
				return Entry{}
			}
		case <-time.After(time.Duration(exp * float64(time.Second))):
			return Entry{}
		}
	}

	entry := processEntry()
	if entry.ID != "" {
		return entry
	}

	// Keep blocking if entry not ready
	if exp == 0 {
		for {
			select {
			case entry := <-client.ch:
				if checkID(id, entry.ID) {
					client.done <- true
					return entry
				}
				client.done <- false
			}
		}
	}

	return Entry{}
}

func (s *stream) autoGenerated(lastId string, id string) (string, error) {
	if id == "*" {
		currentTime := time.Now().UnixMilli()

		if lastId == "" {
			return strconv.FormatInt(currentTime, 10) + "-0", nil
		}

		parts := strings.Split(lastId, "-")
		if len(parts) != 2 {
			return "", nil
		}
		lastTime, _ := strconv.ParseInt(parts[0], 10, 64)
		lastSeq, _ := strconv.Atoi(parts[1])

		if currentTime > lastTime {
			return strconv.FormatInt(currentTime, 10) + "-0", nil
		} else {
			return parts[0] + "-" + strconv.Itoa(lastSeq+1), nil
		}
	}

	v2 := strings.Split(id, "-")

	if len(v2) == 2 && v2[0] != "*" && v2[1] == "*" {
		newTime, _ := strconv.Atoi(v2[0])

		if lastId == "" {
			if newTime == 0 {
				return "0-1", nil
			}
			return v2[0] + "-0", nil
		}

		lastParts := strings.Split(lastId, "-")
		if len(lastParts) != 2 {
			return "", nil
		}
		lastTime, _ := strconv.Atoi(lastParts[0])
		lastSeq, _ := strconv.Atoi(lastParts[1])

		if newTime < lastTime {
			return "", &IDError{Message: "ERR The ID specified in XADD is equal or smaller than the target stream top item"}
		}

		if newTime > lastTime {
			return v2[0] + "-0", nil
		}

		return v2[0] + "-" + strconv.Itoa(lastSeq+1), nil
	}

	return "", nil
}

func (s *stream) validate(lastId, id string) bool {
	if lastId == "" {
		return true
	}

	v1 := strings.Split(lastId, "-")
	v2 := strings.Split(id, "-")

	if len(v1) != 2 || len(v2) != 2 {
		return false
	}

	tv11, _ := strconv.Atoi(v1[0])
	tv12, _ := strconv.Atoi(v1[1])
	tv21, _ := strconv.Atoi(v2[0])
	tv22, _ := strconv.Atoi(v2[1])

	if tv21 > tv11 {
		return true
	} else if tv21 == tv11 {
		return tv22 > tv12
	}
	return false
}
